name: kanonis

services:
  storybook:
    image: ${DESIGN_SYSTEM_IMAGE:-ghcr.io/endeavoury/kanonis-storybook:latest}
    ports:
      - "${STORYBOOK_BIND_ADDRESS:-0.0.0.0}:${STORYBOOK_PORT:-6006}:8080"
    restart: unless-stopped
