import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';

const cssPath = fileURLToPath(new URL('../packages/tokens/src/tokens.css', import.meta.url));
const outputPath = fileURLToPath(new URL('../packages/tokens/src/index.ts', import.meta.url));
const css = await readFile(cssPath, 'utf8');

const firstValues = new Map();
for (const match of css.matchAll(/(--kanonis-[a-z0-9-]+):\s*([^;]+);/g)) {
  if (!firstValues.has(match[1])) firstValues.set(match[1], match[2].replace(/\s+/g, ' ').trim());
}

const groupFor = (name) => {
  if (name.startsWith('--kanonis-color') || name.startsWith('--kanonis-gradient')) return 'color';
  if (/--kanonis-(font|line-height|letter-spacing)/.test(name)) return 'typography';
  if (name.startsWith('--kanonis-space')) return 'spacing';
  if (/--kanonis-(radius|shape)/.test(name)) return 'radius';
  if (/--kanonis-(shadow|elevation)/.test(name)) return 'elevation';
  if (/--kanonis-(duration|ease|motion)/.test(name)) return 'motion';
  if (/--kanonis-(breakpoint|container)/.test(name)) return 'breakpoint';
  if (name.startsWith('--kanonis-z')) return 'zIndex';
  if (name.startsWith('--kanonis-icon')) return 'icon';
  if (/--kanonis-(density|control|target)/.test(name)) return 'density';
  return 'other';
};

const descriptions = {
  '--kanonis-color-bg-canvas': 'Application canvas',
  '--kanonis-color-bg-surface': 'Default component surface',
  '--kanonis-color-bg-elevated': 'Raised and overlay surface',
  '--kanonis-color-text-primary': 'Primary content',
  '--kanonis-color-text-secondary': 'Supporting content',
  '--kanonis-color-text-muted': 'Low-emphasis metadata',
  '--kanonis-color-border-default': 'Default boundary',
  '--kanonis-color-accent-primary': 'Primary interactive accent',
};

const deprecated = {
  '--kanonis-breakpoint-mobile': '--kanonis-breakpoint-compact',
  '--kanonis-breakpoint-tablet': '--kanonis-breakpoint-medium',
  '--kanonis-breakpoint-desktop': '--kanonis-breakpoint-expanded',
};

const describe = (name) =>
  descriptions[name] ??
  name
    .replace('--kanonis-', '')
    .replaceAll('-', ' ')
    .replace(/^./, (letter) => letter.toUpperCase());

const entries = [...firstValues].map(([name, value]) => ({
  name,
  value,
  group: groupFor(name),
  description: describe(name),
  ...(deprecated[name] ? { deprecated: deprecated[name] } : {}),
}));

const raw = `// Generated by scripts/generate-tokens.mjs from tokens.css. Do not edit directly.
export type TokenGroup =
  | 'color'
  | 'typography'
  | 'spacing'
  | 'radius'
  | 'elevation'
  | 'motion'
  | 'breakpoint'
  | 'zIndex'
  | 'icon'
  | 'density'
  | 'other';

export interface DesignToken {
  name: string;
  value: string;
  group: TokenGroup;
  description: string;
  deprecated?: string;
}

export const tokens = ${JSON.stringify(entries, null, 2)} as const satisfies readonly DesignToken[];

export const breakpoints = {
  compact: '${firstValues.get('--kanonis-breakpoint-compact')}',
  medium: '${firstValues.get('--kanonis-breakpoint-medium')}',
  expanded: '${firstValues.get('--kanonis-breakpoint-expanded')}',
  wide: '${firstValues.get('--kanonis-breakpoint-wide')}',
} as const;

export const themes = ['light', 'dark', 'system'] as const;
export type KanonisTheme = (typeof themes)[number];
export const contrasts = ['standard', 'more'] as const;
export type KanonisContrast = (typeof contrasts)[number];
export const brands = ['default', 'finance', 'ontology'] as const;
export type KanonisBrand = (typeof brands)[number];
`;

const generated = await format(raw, { parser: 'typescript', singleQuote: true, printWidth: 100 });
if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) {
    throw new Error('Generated token metadata is stale. Run npm run tokens:generate.');
  }
  console.log(`Token metadata matches ${entries.length} CSS design tokens.`);
} else {
  await writeFile(outputPath, generated);
  console.log(`Generated ${entries.length} typed design tokens.`);
}
