import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { html } from 'lit';

const meta: Meta = { title: 'Components', tags: ['autodocs'] };
export default meta;

export const KanonisButton: StoryObj = { name: 'kanonis-button', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-button>Example</kanonis-button></div>` };
export const KanonisIconButton: StoryObj = { name: 'kanonis-icon-button', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-icon-button>Example</kanonis-icon-button></div>` };
export const KanonisInput: StoryObj = { name: 'kanonis-input', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-input>Example</kanonis-input></div>` };
export const KanonisSearchInput: StoryObj = { name: 'kanonis-search-input', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-search-input>Example</kanonis-search-input></div>` };
export const KanonisSelect: StoryObj = { name: 'kanonis-select', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-select>Example</kanonis-select></div>` };
export const KanonisCheckbox: StoryObj = { name: 'kanonis-checkbox', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-checkbox>Example</kanonis-checkbox></div>` };
export const KanonisFormField: StoryObj = { name: 'kanonis-form-field', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-form-field>Example</kanonis-form-field></div>` };
export const KanonisTextarea: StoryObj = { name: 'kanonis-textarea', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-textarea>Example</kanonis-textarea></div>` };
export const KanonisSwitch: StoryObj = { name: 'kanonis-switch', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-switch>Example</kanonis-switch></div>` };
export const KanonisRange: StoryObj = { name: 'kanonis-range', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-range>Example</kanonis-range></div>` };
export const KanonisBadge: StoryObj = { name: 'kanonis-badge', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-badge>Example</kanonis-badge></div>` };
export const KanonisStatusBadge: StoryObj = { name: 'kanonis-status-badge', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-status-badge>Example</kanonis-status-badge></div>` };
export const KanonisAvatar: StoryObj = { name: 'kanonis-avatar', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-avatar>Example</kanonis-avatar></div>` };
export const KanonisCard: StoryObj = { name: 'kanonis-card', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-card>Example</kanonis-card></div>` };
export const KanonisCodeBlock: StoryObj = { name: 'kanonis-code-block', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-code-block>Example</kanonis-code-block></div>` };
export const KanonisDescriptionList: StoryObj = { name: 'kanonis-description-list', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-description-list>Example</kanonis-description-list></div>` };
export const KanonisPanel: StoryObj = { name: 'kanonis-panel', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-panel>Example</kanonis-panel></div>` };
export const KanonisMetric: StoryObj = { name: 'kanonis-metric', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-metric>Example</kanonis-metric></div>` };
export const KanonisAlert: StoryObj = { name: 'kanonis-alert', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-alert>Example</kanonis-alert></div>` };
export const KanonisLoadingState: StoryObj = { name: 'kanonis-loading-state', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-loading-state>Example</kanonis-loading-state></div>` };
export const KanonisEmptyState: StoryObj = { name: 'kanonis-empty-state', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-empty-state>Example</kanonis-empty-state></div>` };
export const KanonisProgress: StoryObj = { name: 'kanonis-progress', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-progress>Example</kanonis-progress></div>` };
export const KanonisSkeleton: StoryObj = { name: 'kanonis-skeleton', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-skeleton>Example</kanonis-skeleton></div>` };
export const KanonisDisclosure: StoryObj = { name: 'kanonis-disclosure', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-disclosure>Example</kanonis-disclosure></div>` };
export const KanonisDialog: StoryObj = { name: 'kanonis-dialog', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-dialog>Example</kanonis-dialog></div>` };
export const KanonisDrawer: StoryObj = { name: 'kanonis-drawer', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-drawer>Example</kanonis-drawer></div>` };
export const KanonisTooltip: StoryObj = { name: 'kanonis-tooltip', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tooltip>Example</kanonis-tooltip></div>` };
export const KanonisDropZone: StoryObj = { name: 'kanonis-drop-zone', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-drop-zone>Example</kanonis-drop-zone></div>` };
export const KanonisDataTable: StoryObj = { name: 'kanonis-data-table', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-data-table>Example</kanonis-data-table></div>` };
export const KanonisPagination: StoryObj = { name: 'kanonis-pagination', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-pagination>Example</kanonis-pagination></div>` };
export const KanonisDataGrid: StoryObj = { name: 'kanonis-data-grid', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-data-grid>Example</kanonis-data-grid></div>` };
export const KanonisBulkActions: StoryObj = { name: 'kanonis-bulk-actions', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-bulk-actions>Example</kanonis-bulk-actions></div>` };
export const KanonisValidationSummary: StoryObj = { name: 'kanonis-validation-summary', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-validation-summary>Example</kanonis-validation-summary></div>` };
export const KanonisDetailList: StoryObj = { name: 'kanonis-detail-list', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-detail-list>Example</kanonis-detail-list></div>` };
export const KanonisBanner: StoryObj = { name: 'kanonis-banner', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-banner>Example</kanonis-banner></div>` };
export const KanonisFormSection: StoryObj = { name: 'kanonis-form-section', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-form-section>Example</kanonis-form-section></div>` };
export const KanonisDatePicker: StoryObj = { name: 'kanonis-date-picker', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-date-picker>Example</kanonis-date-picker></div>` };
export const KanonisTimePicker: StoryObj = { name: 'kanonis-time-picker', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-time-picker>Example</kanonis-time-picker></div>` };
export const KanonisFileUpload: StoryObj = { name: 'kanonis-file-upload', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-file-upload>Example</kanonis-file-upload></div>` };
export const KanonisStepper: StoryObj = { name: 'kanonis-stepper', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-stepper>Example</kanonis-stepper></div>` };
export const KanonisTaskList: StoryObj = { name: 'kanonis-task-list', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-task-list>Example</kanonis-task-list></div>` };
export const KanonisTimeline: StoryObj = { name: 'kanonis-timeline', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-timeline>Example</kanonis-timeline></div>` };
export const KanonisJobStatus: StoryObj = { name: 'kanonis-job-status', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-job-status>Example</kanonis-job-status></div>` };
export const KanonisRoleBadge: StoryObj = { name: 'kanonis-role-badge', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-role-badge>Example</kanonis-role-badge></div>` };
export const KanonisDiffViewer: StoryObj = { name: 'kanonis-diff-viewer', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-diff-viewer>Example</kanonis-diff-viewer></div>` };
export const KanonisJsonEditor: StoryObj = { name: 'kanonis-json-editor', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-json-editor>Example</kanonis-json-editor></div>` };
export const KanonisMaintenanceNotice: StoryObj = { name: 'kanonis-maintenance-notice', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-maintenance-notice>Example</kanonis-maintenance-notice></div>` };
export const KanonisActionBar: StoryObj = { name: 'kanonis-action-bar', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-action-bar>Example</kanonis-action-bar></div>` };
export const KanonisSplitButton: StoryObj = { name: 'kanonis-split-button', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-split-button>Example</kanonis-split-button></div>` };
export const KanonisInputGroup: StoryObj = { name: 'kanonis-input-group', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-input-group>Example</kanonis-input-group></div>` };
export const KanonisChip: StoryObj = { name: 'kanonis-chip', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-chip>Example</kanonis-chip></div>` };
export const KanonisIllustration: StoryObj = { name: 'kanonis-illustration', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-illustration>Example</kanonis-illustration></div>` };
