import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { html } from 'lit';

const meta: Meta = { title: 'Composites', tags: ['autodocs'] };
export default meta;

export const KanonisButtonGroup: StoryObj = { name: 'kanonis-button-group', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-button-group>Example</kanonis-button-group></div>` };
export const KanonisRadioGroup: StoryObj = { name: 'kanonis-radio-group', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-radio-group>Example</kanonis-radio-group></div>` };
export const KanonisRadio: StoryObj = { name: 'kanonis-radio', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-radio-group><kanonis-radio label="Option"></kanonis-radio></kanonis-radio-group></div>` };
export const KanonisToast: StoryObj = { name: 'kanonis-toast', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-toast-region><kanonis-toast>Notification</kanonis-toast></kanonis-toast-region></div>` };
export const KanonisToastRegion: StoryObj = { name: 'kanonis-toast-region', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-toast-region>Example</kanonis-toast-region></div>` };
export const KanonisTabs: StoryObj = { name: 'kanonis-tabs', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tabs>Example</kanonis-tabs></div>` };
export const KanonisTab: StoryObj = { name: 'kanonis-tab', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tabs><kanonis-tab label="Overview"></kanonis-tab></kanonis-tabs></div>` };
export const KanonisMenu: StoryObj = { name: 'kanonis-menu', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-menu>Example</kanonis-menu></div>` };
export const KanonisMenuItem: StoryObj = { name: 'kanonis-menu-item', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-menu open><kanonis-menu-item>Menu item</kanonis-menu-item></kanonis-menu></div>` };
export const KanonisSidebar: StoryObj = { name: 'kanonis-sidebar', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-sidebar>Example</kanonis-sidebar></div>` };
export const KanonisSidebarItem: StoryObj = { name: 'kanonis-sidebar-item', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-sidebar><kanonis-sidebar-item>Navigation item</kanonis-sidebar-item></kanonis-sidebar></div>` };
export const KanonisBreadcrumbs: StoryObj = { name: 'kanonis-breadcrumbs', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-breadcrumbs>Example</kanonis-breadcrumbs></div>` };
export const KanonisBreadcrumb: StoryObj = { name: 'kanonis-breadcrumb', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-breadcrumbs><kanonis-breadcrumb current>Current page</kanonis-breadcrumb></kanonis-breadcrumbs></div>` };
export const KanonisList: StoryObj = { name: 'kanonis-list', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-list>Example</kanonis-list></div>` };
export const KanonisListItem: StoryObj = { name: 'kanonis-list-item', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-list><kanonis-list-item>List item</kanonis-list-item></kanonis-list></div>` };
export const KanonisTree: StoryObj = { name: 'kanonis-tree', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tree>Example</kanonis-tree></div>` };
export const KanonisTreeItem: StoryObj = { name: 'kanonis-tree-item', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tree><kanonis-tree-item label="Tree item"></kanonis-tree-item></kanonis-tree></div>` };
export const KanonisFilterBuilder: StoryObj = { name: 'kanonis-filter-builder', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-filter-builder>Example</kanonis-filter-builder></div>` };
export const KanonisViewToolbar: StoryObj = { name: 'kanonis-view-toolbar', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-view-toolbar>Example</kanonis-view-toolbar></div>` };
export const KanonisColumnManager: StoryObj = { name: 'kanonis-column-manager', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-column-manager>Example</kanonis-column-manager></div>` };
export const KanonisSavedView: StoryObj = { name: 'kanonis-saved-view', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-saved-view>Example</kanonis-saved-view></div>` };
export const KanonisCombobox: StoryObj = { name: 'kanonis-combobox', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-combobox>Example</kanonis-combobox></div>` };
export const KanonisCommandPalette: StoryObj = { name: 'kanonis-command-palette', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-command-palette>Example</kanonis-command-palette></div>` };
export const KanonisGlobalSearch: StoryObj = { name: 'kanonis-global-search', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-global-search>Example</kanonis-global-search></div>` };
export const KanonisTenantSwitcher: StoryObj = { name: 'kanonis-tenant-switcher', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tenant-switcher>Example</kanonis-tenant-switcher></div>` };
export const KanonisUserMenu: StoryObj = { name: 'kanonis-user-menu', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-user-menu>Example</kanonis-user-menu></div>` };
export const KanonisWorkspaceTabs: StoryObj = { name: 'kanonis-workspace-tabs', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-workspace-tabs>Example</kanonis-workspace-tabs></div>` };
export const KanonisNavigationGroup: StoryObj = { name: 'kanonis-navigation-group', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-navigation-group>Example</kanonis-navigation-group></div>` };
export const KanonisContextMenu: StoryObj = { name: 'kanonis-context-menu', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-context-menu>Example</kanonis-context-menu></div>` };
export const KanonisQuickActions: StoryObj = { name: 'kanonis-quick-actions', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-quick-actions>Example</kanonis-quick-actions></div>` };
export const KanonisRecordHeader: StoryObj = { name: 'kanonis-record-header', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-record-header>Example</kanonis-record-header></div>` };
export const KanonisNotificationCenter: StoryObj = { name: 'kanonis-notification-center', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-notification-center>Example</kanonis-notification-center></div>` };
export const KanonisFieldArray: StoryObj = { name: 'kanonis-field-array', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-field-array>Example</kanonis-field-array></div>` };
export const KanonisApprovalFlow: StoryObj = { name: 'kanonis-approval-flow', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-approval-flow>Example</kanonis-approval-flow></div>` };
export const KanonisActivityFeed: StoryObj = { name: 'kanonis-activity-feed', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-activity-feed>Example</kanonis-activity-feed></div>` };
export const KanonisChangeSummary: StoryObj = { name: 'kanonis-change-summary', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-change-summary>Example</kanonis-change-summary></div>` };
export const KanonisAuditLog: StoryObj = { name: 'kanonis-audit-log', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-audit-log>Example</kanonis-audit-log></div>` };
export const KanonisPermissionMatrix: StoryObj = { name: 'kanonis-permission-matrix', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-permission-matrix>Example</kanonis-permission-matrix></div>` };
export const KanonisCodeEditor: StoryObj = { name: 'kanonis-code-editor', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-code-editor>Example</kanonis-code-editor></div>` };
export const KanonisHelpPanel: StoryObj = { name: 'kanonis-help-panel', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-help-panel>Example</kanonis-help-panel></div>` };
export const KanonisTour: StoryObj = { name: 'kanonis-tour', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-tour>Example</kanonis-tour></div>` };
export const KanonisCoachmark: StoryObj = { name: 'kanonis-coachmark', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-coachmark>Example</kanonis-coachmark></div>` };
export const KanonisCompareView: StoryObj = { name: 'kanonis-compare-view', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-compare-view>Example</kanonis-compare-view></div>` };
export const KanonisSegmentedControl: StoryObj = { name: 'kanonis-segmented-control', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-segmented-control>Example</kanonis-segmented-control></div>` };
export const KanonisSegment: StoryObj = { name: 'kanonis-segment', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-segmented-control><kanonis-segment label="Option"></kanonis-segment></kanonis-segmented-control></div>` };
export const KanonisReorderList: StoryObj = { name: 'kanonis-reorder-list', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-reorder-list>Example</kanonis-reorder-list></div>` };
export const KanonisReorderItem: StoryObj = { name: 'kanonis-reorder-item', render: () => html`<div style="padding:2rem;max-width:960px"><kanonis-reorder-list><kanonis-reorder-item label="Reorder item"></kanonis-reorder-item></kanonis-reorder-list></div>` };
